-- Create the bowling database
CREATE DATABASE bowling;

-- Connect to it
\c bowling;

-- Core table
CREATE TABLE Core (
    ID SERIAL PRIMARY KEY,
    NAME TEXT,
    DESCRIPTION TEXT,
    TYPE TEXT
);                                  

-- CoverStock table
CREATE TABLE CoverStock (
    ID SERIAL PRIMARY KEY,
    NAME TEXT,
    DESCRIPTION TEXT,
    TYPE TEXT
);

-- Ball table
CREATE TABLE Ball (
    ID SERIAL PRIMARY KEY,
    CORE_ID INT REFERENCES Core(ID),
    COVERSTOCK_ID INT REFERENCES CoverStock(ID),
    NAME TEXT,
    IMAGE TEXT,
    BRAND TEXT,
    RELEASE_DATE DATE,
    DISCONTINUED BOOLEAN,
    OVERSEAS BOOLEAN,
    FACTORY_FINISH TEXT,
    EARLY_V_LATE REAL,
    SMOOTH_V_ANGULAR REAL,
    HOOK_POTENTIAL REAL
);

-- Specs table
CREATE TABLE Specs (
    BALL_ID INT REFERENCES Ball(ID),
    WEIGHT INT,
    RG REAL,
    DIFF REAL,
    MB_DIFF REAL,
    -- EARLY_V_LATE REAL,
    -- SMOOTH_V_ANGULAR REAL,
    -- HOOK_POTENTIAL REAL,
    PRIMARY KEY (BALL_ID, WEIGHT)
);